# Generated by Django 3.0.5 on 2020-04-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERID', models.CharField(default='', max_length=30, unique=True)),
                ('USERUID', models.CharField(default='', max_length=20, unique=True)),
                ('PHONENUM', models.IntegerField(unique=True)),
                ('CI', models.CharField(default='', max_length=100, unique=True)),
                ('IMEI', models.CharField(default='', max_length=20, unique=True)),
                ('NICKNAME', models.CharField(default='', max_length=10, unique=True)),
                ('RECENTPAYAVG', models.IntegerField()),
                ('SIGNUPDATE', models.DateTimeField(auto_now_add=True)),
                ('PROFILEIMG', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
    ]
