# Generated by Django 3.0.5 on 2020-05-11 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobet_app', '0002_auto_20200511_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='IMEI',
        ),
    ]
