# Generated by Django 3.0.5 on 2020-05-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobet_app', '0003_remove_user_imei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='PHONENUM',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
