# Generated by Django 3.0.5 on 2020-05-13 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobet_app', '0005_auto_20200512_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionset',
            name='CATEGORYCODE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competition', to='mobet_app.categoryList'),
        ),
        migrations.AlterField(
            model_name='competitionset',
            name='OWNER_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competition', to='mobet_app.User'),
        ),
        migrations.AlterField(
            model_name='financeinfo',
            name='CATEGORYCODE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance', to='mobet_app.categoryList'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='ROOMNAME',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='mobet_app.competitionSet'),
        ),
        migrations.AlterField(
            model_name='participatedlist',
            name='ROOMNUM_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participated', to='mobet_app.competitionSet'),
        ),
        migrations.AlterField(
            model_name='participatedlist',
            name='USER_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participated', to='mobet_app.User'),
        ),
        migrations.AlterField(
            model_name='usergamerecord',
            name='ROOMNUM_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_record', to='mobet_app.competitionSet'),
        ),
        migrations.AlterField(
            model_name='usergamerecord',
            name='USER_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_record', to='mobet_app.User'),
        ),
    ]
