# Generated by Django 3.0.5 on 2020-05-13 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobet_app', '0006_auto_20200513_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylist',
            name='CATEGORY',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='competitionset',
            name='CATEGORYCODE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition', to='mobet_app.categoryList'),
        ),
        migrations.AlterField(
            model_name='competitionset',
            name='RECENTPAYAVGMAX',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='competitionset',
            name='RECENTPAYAVGMIN',
            field=models.IntegerField(null=True),
        ),
    ]
