# Generated by Django 3.0.5 on 2020-05-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobet_app', '0007_auto_20200513_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionset',
            name='ROOMNAME',
            field=models.CharField(default='', max_length=30),
        ),
    ]
