# Generated by Django 3.0.5 on 2020-05-14 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobet_app', '0011_notification_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='USER_ID',
        ),
    ]
