# Generated by Django 3.0.5 on 2020-05-14 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobet_app', '0013_notification_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='ROOMNAME',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='mobet_app.competitionSet'),
        ),
    ]
