# Generated by Django 3.0.5 on 2020-05-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobet_app', '0014_auto_20200514_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='participatedlist',
            name='LEFTMONEY',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='TIMELOG',
            field=models.DateTimeField(null=True),
        ),
    ]
