# Generated by Django 3.0.5 on 2020-05-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobet_app', '0015_auto_20200514_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrank',
            name='GAMECOUNT',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userrank',
            name='POINTS',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='userrank',
            name='WINRECORD',
            field=models.IntegerField(default=0),
        ),
    ]
