# Generated by Django 3.0.5 on 2020-05-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobet_app', '0016_auto_20200515_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergamerecord',
            name='LEFTMONEY',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
