# Generated by Django 3.0.5 on 2020-05-19 23:57

from django.db import migrations, models
import django.utils.timezone
import mobet_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('mobet_app', '0020_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='img',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='usr'),
            preserve_default=False,
        ),
    ]
