# Generated by Django 3.0.5 on 2020-05-20 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobet_app', '0021_auto_20200519_2357'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
