# Generated by Django 3.0.5 on 2020-05-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobet_app', '0023_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionset',
            name='IS_FINISHED',
            field=models.BooleanField(default=False),
        ),
    ]
