# Generated by Django 3.0.5 on 2020-05-21 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobet_app', '0025_auto_20200520_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionset',
            name='CATEGORYCODE',
        ),
        migrations.RemoveField(
            model_name='competitionset',
            name='OWNER_ID',
        ),
        migrations.RemoveField(
            model_name='financeinfo',
            name='CATEGORYCODE',
        ),
        migrations.RemoveField(
            model_name='financeinfo',
            name='USER_ID',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='OWNER_ID',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='ROOMNAME',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='USER_ID',
        ),
        migrations.RemoveField(
            model_name='participatedlist',
            name='ROOMNUM_ID',
        ),
        migrations.RemoveField(
            model_name='participatedlist',
            name='USER_ID',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='USERONE',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='USERTWO',
        ),
        migrations.RemoveField(
            model_name='usergamerecord',
            name='ROOMNUM_ID',
        ),
        migrations.RemoveField(
            model_name='usergamerecord',
            name='USER_ID',
        ),
        migrations.RemoveField(
            model_name='userrank',
            name='USER_ID',
        ),
        migrations.DeleteModel(
            name='categoryList',
        ),
        migrations.DeleteModel(
            name='competitionSet',
        ),
        migrations.DeleteModel(
            name='financeInfo',
        ),
        migrations.DeleteModel(
            name='notification',
        ),
        migrations.DeleteModel(
            name='participatedList',
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='userGameRecord',
        ),
        migrations.DeleteModel(
            name='userRank',
        ),
    ]
