# Generated by Django 3.0.5 on 2020-05-21 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobet_app', '0026_auto_20200521_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CATEGORY', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ('CATEGORY',),
            },
        ),
        migrations.CreateModel(
            name='competitionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ROOMNAME', models.CharField(default='', max_length=30)),
                ('STARTDATE', models.DateTimeField()),
                ('DUEDATE', models.DateTimeField()),
                ('SETTINGMONEY', models.IntegerField()),
                ('RECENTPAYAVGMIN', models.IntegerField(null=True)),
                ('RECENTPAYAVGMAX', models.IntegerField(null=True)),
                ('OPEN', models.BooleanField(default=True)),
                ('IS_FINISHED', models.BooleanField(default=False)),
                ('CATEGORYCODE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition', to='mobet_app.categoryList')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERID', models.CharField(default='', max_length=30, unique=True)),
                ('USERUID', models.CharField(default='', max_length=50, unique=True)),
                ('PHONENUM', models.CharField(default='', max_length=20, unique=True)),
                ('NICKNAME', models.CharField(default='', max_length=10, unique=True)),
                ('RECENTPAYAVG', models.IntegerField(null=True)),
                ('SIGNUPDATE', models.DateTimeField(auto_now_add=True)),
                ('PROFILEIMG', models.CharField(default='', max_length=100, null=True)),
                ('TIMELOG', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='userRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GRADE', models.CharField(default='', max_length=5)),
                ('POINTS', models.IntegerField(default=500)),
                ('WINRECORD', models.IntegerField(default=0)),
                ('GAMECOUNT', models.IntegerField(default=0)),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rank', to='mobet_app.User')),
            ],
            options={
                'ordering': ('-POINTS',),
            },
        ),
        migrations.CreateModel(
            name='userGameRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUCCESSES', models.BooleanField(default=False)),
                ('RECORDDATE', models.DateTimeField(auto_now=True)),
                ('GAMEGRADE', models.IntegerField(default=1)),
                ('LEFTMONEY', models.IntegerField()),
                ('ROOMNUM_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_record', to='mobet_app.competitionSet')),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_record', to='mobet_app.User')),
            ],
            options={
                'ordering': ('ROOMNUM_ID', 'GAMEGRADE'),
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERONE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_one', to='mobet_app.User')),
                ('USERTWO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_two', to='mobet_app.User')),
            ],
            options={
                'ordering': ('USERONE',),
            },
        ),
        migrations.CreateModel(
            name='participatedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LEFTMONEY', models.IntegerField()),
                ('ROOMNUM_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participated', to='mobet_app.competitionSet')),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participated', to='mobet_app.User')),
            ],
            options={
                'ordering': ('ROOMNUM_ID', '-LEFTMONEY'),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ALARM', models.BooleanField(default=False)),
                ('OWNER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='mobet_app.User')),
                ('ROOMNAME', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='mobet_app.competitionSet')),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_user', to='mobet_app.User')),
            ],
            options={
                'ordering': ('OWNER_ID',),
            },
        ),
        migrations.CreateModel(
            name='financeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PAYMENTTIME', models.DateTimeField()),
                ('PAYMENTPRICE', models.IntegerField()),
                ('INANDOUT', models.BooleanField(default=True)),
                ('CATEGORYCODE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance', to='mobet_app.categoryList')),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance', to='mobet_app.User')),
            ],
            options={
                'ordering': ('PAYMENTTIME',),
            },
        ),
        migrations.AddField(
            model_name='competitionset',
            name='OWNER_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competition', to='mobet_app.User'),
        ),
    ]
