# Generated by Django 3.0.5 on 2020-05-22 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobet_app', '0028_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
