# Generated by Django 3.0.5 on 2020-05-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobet_app', '0030_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeinfo',
            name='STORE',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
