# Generated by Django 3.0.5 on 2020-05-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobet_app', '0032_auto_20200523_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='participatedlist',
            name='TIMELOG',
            field=models.DateTimeField(null=True),
        ),
    ]
